#!/usr/bin/php

<?php

define('ROOT', dirname(dirname(__FILE__)));
define('DS', "/");

require(ROOT."/script/script_includes.php");

if (isset($argv[1]) && isset($argv[2])) {

	$controller_name = string_to_camel($argv[2]);
	$model_name = inflection::singularize(camel_to_underscore($controller_name));
	$capital_controller_name = camel_to_string($controller_name);
	$capital_model_name = underscore_to_string($model_name);

	if ($argv[1] == "model" || $argv[1] == "controller") {

		// generate model

		if (!file_exists(ROOT."/application/models/".$model_name.".php")) {
			$model_template = file_get_contents(ROOT."/library/templates/model.php");

			$model_template = str_replace("<%MODEL_NAME%>", $model_name, $model_template);
			$model_template = str_replace("<%CAPITAL_MODEL_NAME%>", $capital_model_name, $model_template);

			file_put_contents(ROOT."/application/models/".$model_name.".php", $model_template);

			echo "'$capital_model_name' model created\n";
		}
		else {
			echo "The model '$model_name' already exists\n";
		}

		// generate example structure file

		if (!file_exists(ROOT."/application/structures/".$model_name.".php")) {
			$structure_template = file_get_contents(ROOT."/library/templates/structure.php");

			file_put_contents(ROOT."/application/structures/".$model_name.".php", $structure_template);

			echo "'$capital_model_name' structure created\n";
		}
		else {
			echo "The structure '$model_name' already exists\n";
		}
	}


	if ($argv[1] == 'controller') {

		// generate controller

		if (!file_exists(ROOT."/application/controllers/".$controller_name.".php")) {
			$controller_template = file_get_contents(ROOT."/library/templates/controller.php");

			$controller_template = str_replace("<%CONTROLLER_NAME%>", $controller_name, $controller_template);
			$controller_template = str_replace("<%CAPITAL_CONTROLLER_NAME%>", $capital_controller_name, $controller_template);
			$controller_template = str_replace("<%MODEL_NAME%>", $model_name, $controller_template);
			$controller_template = str_replace("<%CAPITAL_MODEL_NAME%>", $capital_model_name, $controller_template);

			file_put_contents(ROOT."/application/controllers/".$controller_name.".php", $controller_template);

			echo "'$capital_controller_name' controller created\n";
		}
		else {
			echo "The controller '$controller_name' already exists\n";
		}

		// generate helper

		if (!file_exists(ROOT."/application/helpers/".$controller_name.".php")) {
			$helper_template = file_get_contents(ROOT."/library/templates/helper.php");

			$helper_template = str_replace("<%CONTROLLER_NAME%>", $controller_name, $helper_template);
			$helper_template = str_replace("<%CAPITAL_CONTROLLER_NAME%>", $capital_controller_name, $helper_template);

			file_put_contents(ROOT."/application/helpers/".$controller_name.".php", $helper_template);

			echo "'$capital_controller_name' helper created\n";
		}
		else {
			echo "The helper '$controller_name' already exists\n";
		}

		// generate views

		if (!file_exists(ROOT.'/application/views/'.camel_to_underscore($controller_name))) {
    		mkdir(ROOT.'/application/views/'.camel_to_underscore($controller_name), 0777, true);
    	}
		foreach (getDirectoryList(ROOT.'/library/templates/views') as $file) {

			if (!file_exists(ROOT."/application/views/".camel_to_underscore($controller_name)."/".$file)) {

				$data = file_get_contents(ROOT.'/library/templates/views/'.$file);
				$data = str_replace("<%CONTROLLER_NAME%>", $controller_name, $data);
				$data = str_replace("<%CAPITAL_CONTROLLER_NAME%>", $capital_controller_name, $data);
				$data = str_replace("<%MODEL_NAME%>", $model_name, $data);
				$data = str_replace("<%CAPITAL_MODEL_NAME%>", $capital_model_name, $data);

				file_put_contents(ROOT."/application/views/".camel_to_underscore($controller_name)."/".$file, $data);

				echo "'".camel_to_underscore($controller_name)."' $file view created\n";

			}
			else {
				echo "The helper '".camel_to_underscore($controller_name)."' $file view exists\n";
			}


		}


	}
	else return;
}
else return;
?>
